export const worlds = [
  {
    slug: "how-software-works",
    title: "How Software Actually Works",
    summary: "Follow a click from the browser to a server, a database, and back.",
    order: 1,
    status: "playable",
    levels: [
      {
        slug: "the-click-is-not-the-login",
        title: "The click is not the login",
        summary: "Put the real steps of a login in order and say what each one does.",
        concept: "A user interface event starts a request. It is not the request.",
        whyItMatters: "When login breaks, you have to know which machine failed.",
        order: 1,
      },
      {
        slug: "a-login-you-can-defend",
        title: "A login you can defend",
        summary: "Place the pieces of a login and connect only the ones that should talk.",
        concept: "The browser talks to an API. The API talks to secrets and data.",
        whyItMatters: "This is the shape of almost every feature you will ask an agent to build.",
        order: 2,
      },
    ],
  },
  {
    slug: "programming-fundamentals",
    title: "Programming and CS Fundamentals",
    summary: "Data, functions, async work, and the structures real apps use.",
    order: 2,
    status: "coming_soon",
    levels: [],
  },
  {
    slug: "databases-and-data",
    title: "Databases and Data",
    summary: "Model the rows a product actually needs, including who belongs where.",
    order: 3,
    status: "playable",
    levels: [
      {
        slug: "users-and-organizations",
        title: "Users and organizations",
        summary: "Design tables for people who can belong to more than one organization.",
        concept: "Many-to-many relationships need a join table and foreign keys.",
        whyItMatters: "A wrong relationship shows up as overwritten customers, not as a theory error.",
        order: 1,
      },
    ],
  },
  {
    slug: "software-architecture",
    title: "Software Architecture",
    summary: "Queues, workers, caches, and what to do when a request is too slow.",
    order: 4,
    status: "coming_soon",
    levels: [],
  },
  {
    slug: "authentication-security",
    title: "Authentication and Security",
    summary: "Prove who is calling, then decide what that caller is allowed to touch.",
    order: 5,
    status: "playable",
    levels: [
      {
        slug: "the-invoice-that-is-not-yours",
        title: "The invoice that is not yours",
        summary: "A signed-in user can read another customer's invoice. Find the hole.",
        concept: "Authentication is not authorization.",
        whyItMatters: "This bug ships constantly in generated CRUD code.",
        order: 1,
      },
    ],
  },
  {
    slug: "testing-and-quality",
    title: "Testing and Code Quality",
    summary: "Decide which tests must exist before a change is allowed to ship.",
    order: 6,
    status: "coming_soon",
    levels: [],
  },
  {
    slug: "git-and-workflows",
    title: "Git and Team Workflows",
    summary: "Branches, review, conflicts, and a main branch you can trust.",
    order: 7,
    status: "coming_soon",
    levels: [],
  },
  {
    slug: "cloud-and-devops",
    title: "Cloud and DevOps",
    summary: "What happens between a push and a customer using the app.",
    order: 8,
    status: "coming_soon",
    levels: [],
  },
  {
    slug: "production-engineering",
    title: "Production Engineering",
    summary: "Logs, retries, and the incident where customers are charged twice.",
    order: 9,
    status: "playable",
    levels: [
      {
        slug: "the-double-charge",
        title: "The double charge",
        summary: "Stripe is flaky, customers retry, and some of them pay twice.",
        concept: "A retried request must be safe to repeat.",
        whyItMatters: "Timeouts happen. The second click is part of the design.",
        order: 1,
      },
    ],
  },
  {
    slug: "ai-native-engineering",
    title: "AI Native Engineering",
    summary: "The agent can write the code. You own the explanation and the decision.",
    order: 10,
    status: "playable",
    levels: [
      {
        slug: "explain-it-to-the-senior",
        title: "Explain it to the senior",
        summary: "Walk a login design in plain language a senior engineer can push on.",
        concept: "If you cannot explain it, you do not own it yet.",
        whyItMatters: "This is the conversation that happens in review and in interviews.",
        order: 1,
      },
    ],
  },
] as const;
